backend/base/urls.py
from django.urls import path
from django.conf.urls import handler404
from . import views

handler404 = views.custom_404

urlpatterns = [
    path('', views.home, name='home'),
    path('leaderboard', views.leaderboard_view, name='leaderboard'),
    path('dashboard', views.dashboard_view, name='dashboard'),
    path('message/<int:id>', views.message_view, name='message'),
    path('about', views.about_view, name='about'),
    path('blogs', views.blogs_view, name='blogs'),
    path('blogs/<str:blog_id>', views.blog_view, name='blog'),
    path('contact', views.contact_view, name='contact'),
    path('terms_and_conditions', views.terms_conditions_view, name='terms_conditions'),
    path('downloads', views.downloads_view, name='downloads'),
    path('search/users', views.search_users_view, name='search_users'),
]

backend/brainbunny/urls.py
import environ
import os

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)

)

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ["127.0.0.1", "brainbunny.up.railway.app"]

CSRF_TRUSTED_ORIGINS = ["https://brainbunny.up.railway.app"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'base',
    'quiz',
    'ckeditor',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'brainbunny.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brainbunny.wsgi.application'

LOGIN_URL = 'login'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # or os.path.join(BASE_DIR, "static")

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
if not DEBUG:
            AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
            AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
            AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
# AWS_S3_REGION_NAME = 'us-east-2' 

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
# AWS_QUERYSTRING_AUTH = False

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

STATICFILES_STORAGES = 'storages.backends.s3boto3.S3Boto3Storage'

backend/quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_quiz, name='all_quiz'),
    path('<int:quiz_id>/', views.quiz_view, name='quiz_view'),
]

backend/quiz/models.py
from django.db import models
import pandas as pd
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver
from smart_open import open
import io

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quiz_file = models.FileField(upload_to='quiz/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return self.title

    # call the function on quiz save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.quiz_file:
            self.import_quiz_from_excel()

    # function to extract excel file
    def import_quiz_from_excel(self):
        # Use self.quiz_file.url to get the S3 file URL
        s3_url = self.quiz_file.url

        # Use smart_open to read the Excel file from S3
        with open(s3_url, 'rb') as file:
            # Load the Excel file content into a pandas DataFrame
            df = pd.read_excel(io.BytesIO(file.read()))

        # iterate over the each row
        for index, row in df.iterrows():
            # extract question text, choices and correct answer from the row
            question_text = row['Question']
            choice1 = row['A']
            choice2 = row['B']
            choice3 = row['C']
            choice4 = row['D']
            correct_answer = row['Answer']

            # create the question object
            question = Question.objects.get_or_create(quiz=self, text=question_text)

            # create choices objects
            choice_1 = Choice.objects.get_or_create(question=question[0], text=choice1, is_correct=correct_answer == 'A')
            choice_2 = Choice.objects.get_or_create(question=question[0], text=choice2, is_correct=correct_answer == 'B')
            choice_3 = Choice.objects.get_or_create(question=question[0], text=choice3, is_correct=correct_answer == 'C')
            choice_4 = Choice.objects.get_or_create(question=question[0], text=choice4, is_correct=correct_answer == 'D')

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text[:50]
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.question.text[:50]}, {self.text[:20]}"

class QuizSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}, {self.quiz.title}"

class UserRank(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.IntegerField(null=True, blank=True)
    total_score = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.rank}, {self.user.username}"

    @receiver(post_save, sender=QuizSubmission)
    def update_leaderboard(sender, instance, created, **kwargs):
        if created:
            update_leaderboard()



def update_leaderboard():
    # Count the sum of scores for all users
    user_scores = (QuizSubmission.objects.values('user').annotate(total_score=Sum('score')).order_by('-total_score'))

    # Update rank based on the sorted list
    rank = 1
    for entry in user_scores:
        user_id = entry['user']
        total_score = entry['total_score']

        user_rank, created = UserRank.objects.get_or_create(user_id=user_id)
        user_rank.rank = rank
        user_rank.total_score = total_score
        user_rank.save()

        rank += 1

backend/quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from account.models import Profile
from .models import Quiz, Category
from django.db.models import Q
from quiz.models import QuizSubmission
from django.contrib import messages

# Create your views here.

@login_required
def all_quiz_view(request):

    quizzes = Quiz.objects.order_by('-created_at')
    categories = Category.objects.all()

    context = {"quizzes": quizzes, "categories": categories}
    return render(request, 'all-quiz.html', context)

@login_required
def search_view(request, category):

    # search by search bar
    if request.GET.get('q') != None:
        q = request.GET.get('q')
        query = Q(title__icontains=q) | Q(description__icontains=q)
        quizzes = Quiz.objects.filter(query).order_by('-created_at')
    
    # search by category
    elif category != " ":
        quizzes = Quiz.objects.filter(category__name=category).order_by('-created_at')
    
    else:
        quizzes = Quiz.objects.order_by('-created_at')


    categories = Category.objects.all()

    context = {"quizzes": quizzes, "categories": categories}
    return render(request, 'all-quiz.html', context)

@login_required
def quiz_view(request, quiz_id):

    quiz = get_object_or_404(Quiz, pk=quiz_id)

    if request.method == "POST":
        
        # Get the score
        score = int(request.POST.get('score', 0))
        
        # save the new quiz submission
        submission = QuizSubmission(user=request.user, quiz=quiz, score=score)
        submission.save()

        return redirect('quiz_result', submission_id=submission.id)

    return render(request, 'quiz.html', {'quiz': quiz})

@login_required
def quiz_result_view(request, submission_id):

    submission = get_object_or_404(QuizSubmission, pk=submission_id, user=request.user)
    context = {'submission': submission}
    return render(request, 'quiz-result.html', context)

backend/templates/blogs.html
{% extends 'index.html' %}
{% block title %}Blogs - BrainBunny{% endblock title %}

{% block content %}

<h1 class="display-4 text-center my-5">Blogs</h1>

<main>
    <div class="container col-md-6 col-sm-12">
        {% for year_count in year_blog_count %}
        <h3>{{year_count.year}} - ({{year_count.count}} blogs)</h3>
        <ul class="list mb-4 p-3">
            {% for blog in blogs %}
            {% if blog.created_at|date:"Y" == year_count.year|stringformat:"s" %}
            <li class="d-flex justify-content-between mb-2">
                <a href="{% url 'blog' blog.id %}">{{blog.title}}</a>
                <span class="text-secondary">{{blog.created_at}}</span>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endfor %}
        
    </div>
</main>

{% endblock content %}

backend/templates/confirm.html
{% extends 'index.html' %}

{% block title %}@{{request.user.username}} Profile Delete Confirmation - BrainBunny{% endblock title %}

{% block content %}


<h1 class="display-4 text-center my-5">Confirmation Page</h1>

  <div class="container">
    <form action="" method="POST" class="">
        {% csrf_token %}
        <p class="fs-4"><b>@{{request.user.username}}</b>, Are you sure you want to delete your profile??</p>
        <a href="{% url 'profile' request.user.username %}" class="btn btn-success" type="button">Back to Profile</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
  </div>

{% endblock content %}

backend/templates/contact.html
{% extends 'index.html' %}
{% block title %}Contact Us - BrainBunny{% endblock title %}

{% block content %}

<h1 class="display-4 text-center my-5">Contact Us</h1>

<main>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<form action="" method="post" class="contact-form">
					{% csrf_token %}
					<div class="form-group mb-4">
						<label for="username">Username</label>
						<input type="text" id="username" name="username" value="{{request.user.username}}" class="form-control" disabled>
					</div>

					<div class="form-group mb-4">
						<label for="subject">Subject</label>
						<input type="text" id="subject" name="subject" required class="form-control">
					</div>

					<div class="form-group mb-4">
						<label for="message">Message</label>
						<textarea id="message" name="message" rows="5" required class="form-control"></textarea>
					</div>

					<button type="submit" class="btn btn-primary btn-block">Send Message</button>
				</form>
			</div>
		</div>
	</div>
</main>

{% endblock content %}

backend/templates/dashboard.html
{% extends 'index.html' %}
{% block title %}Dashboard - BrainBunny{% endblock title %}

{% block content %}

    <h1 class="display-4 text-center my-5">Dashboard</h1>

    <!-- Dashboard Code Goes Here -->
    <div class="container">
        <div class="row">
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_users}}</h1>
                        <p class="card-text">Active Users</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_users}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_users|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_quizzes}}</h1>
                        <p class="card-text">Quizzes</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_quizzes}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_quizzes|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_quiz_submit}}</h1>
                        <p class="card-text">Submissions</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_quiz_submit}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_quiz_submit|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_questions}}</h1>
                        <p class="card-text">Questions</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_questions}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_questions|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-12 mb-3">
                <h2 class="mb-3 text-center">Inbox</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">User</th>
                            <th scope="col">Subject</th>
                            <th scope="col">Time</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in messages %}
                        <tr class="table-{% if not message.is_read %}active{% endif %}">
                            <th scope="row">{{forloop.counter}}</th>
                            <td><a href="{% url 'profile' message.user.username %}">@{{message.user.username}}</a></td>
                            <td>{{message.subject}}</td>
                            <td>{{message.created_at}}</td>
                            <td><a href="{% url 'message' message.id %}" class="btn btn-sm btn-primary">Open</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

backend/templates/downloads.html
{% extends 'index.html' %}
{% block title %}Downloads - BrainBunny{% endblock title %}

{% block content %}
<h1 class="display-4 text-center my-5">Downloads</h1>

<main>
    <div class="container col-md-8 col-sm-12">
        <div class="download-item mb-4">
            <h2 class="">Research Paper 1</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                explicabo eos molestias enim itaque, quis nam.</p>
            <a href="" class="btn btn-primary">Download</a>
            <hr>
        </div>
        <div class="download-item mb-4">
            <h2>Reports</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                explicabo eos molestias enim itaque, quis nam.</p>
            <a href="" class="btn btn-primary">Download</a>
            <hr>
        </div>
        <div class="download-item mb-4">
            <h2>Research Paper 1</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                explicabo eos molestias enim itaque, quis nam.</p>
            <a href="" class="btn btn-primary">Download</a>
            <hr>
        </div>
    </div>
</main>

{% endblock content %}

backend/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Welcome to BrainBunny{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
        integrity="sha512-ZnR2wlLbSbr8/c9AgLg3jQPAattCUImNsae6NHYnS9KrIwRdcY9DxFotXhNAKIKbAXlRnujIqUWoXXwqyFOeIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    {% include "components/navbar.html" %}

    {% block content %}

    {% endblock content %}

    {% include "components/footer.html" %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>

    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
</body>

</html>

backend/templates/profile.html
{% extends 'index.html' %}

{% block title %}@{{user_profile2.user.username}}'s Profile - BrainBunny{% endblock title %}

{% block content %}

    <h1 class="display-4 text-center my-5">@{{user_profile2.user.username}}'s Profile</h1>
    <div class="mb-3">
        {% for message in messages %}
        <h5 class="text-{{message.level_tag}} text-center">{{message}}</h5>
        {% endfor %}
      </div>
    <div class="container text-center">
        {% if request.user.username == user_profile2.user.username %}
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a href="{% url 'edit_profile' %}" type="button" class="btn btn-outline-primary">Edit</a>
            <a href="{% url 'delete_profile' %}" type="button" class="btn btn-outline-danger">Delete</a>
        </div>
        {% endif %}

        <div class="container text-center my-4">
            <div class="row row-cols-sm-1 row-cols-md-2">
                <div class="col-12">
                    <img src="{{user_profile2.profile_img.url}}" alt="user-profile" class="rounded-circle" width="150" height="150">
                    <h2 class="fs-3">@{{user_profile2.user.username}}</h2>
                </div>
                <div class="col-12">
                    <h2>{{user_profile2.user.first_name|default:"Full name not available"}} {{user_profile2.user.last_name}}</h2>
                    <p class="fs-5"><i class="bi bi-gender-ambiguous"></i> {{user_profile2.gender|default:'Gender Not Available'}}</p>
                    <p class="fs-5"><i class="bi bi-geo-alt-fill"></i> {{user_profile2.location|default:'Location Not Available'}}</p>
                    <p class="fs-5"><i class="bi bi-file-person"></i> {{user_profile2.bio|default:'Bio Not Available'}}</p>
                    {% if request.user.is_superuser %}
                    <p class="fs-5"><i class="bi bi-envelope-at"></i> <a href="mailto:{{user_profile2.user.email}}"> {{user_profile2.user.email|default:'Email Not Available'}}</a></p>
                    {% endif %}
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="container">
            <div class="row row-cols-sm-1 row-cols-md-1 row-cols-lg-1">
                <div class="col-12">
                    <h3>Quiz attended by @{{user_profile2.user.username}}</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Quiz</th>
                                <th scope="col">Marks</th>
                                <th scope="col">Time</th>
                                <th scope="col">Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for submission in submissions %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td title="{{submission.quiz.title}}">{{submission.quiz.title|truncatewords:6}}</td>
                                <td>{{submission.score}}/{{submission.quiz.question_set.all|length}}</td>
                                <td>{{submission.submitted_at|timesince}} ago</td>
                                <td>
                                    <a href="{% url 'quiz_result' submission.id %}">Detail</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

backend/templates/quiz.html
{% extends 'index.html' %}

{% block title %}{{quiz.title}} - BrainBunny{% endblock title %}

{% block content %}
    <style>
        .questions {
            user-select: none;
        }
    </style>

    <h1 class="display-4 text-center my-5">{{quiz.title}} - ({{quiz.question_set.all|length}})</h1>
    <p class="fs-4 text-center container">{{quiz.description}}</p>

    <div class="container">
        <div class="d-flex justify-content-between">
            <span class="fs-5">{{quiz.created_at}}</span>
            <span class="fs-5" id="timer">10:00</span>
        </div>

        {% for message in messages %}
        <div id="message-div">
            <h4 class="text-center text-success">{{message}}</h4>
        </div>
        {% endfor %}


        <div class="questions my-4">
            {% for question in quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold">
                    Question {{forloop.counter}}
                </div>
                <div class="card-body">
                    <p class="card-text">{{question.text}}</p>
                    {% for option in question.choice_set.all %}
                    <div class="form-check">
                        <label class="form-check-label" for="{{option.id}}">
                            <input class="form-check-input" value="{{option.text}}" type="radio" name="{{option.question.id}}" id="{{option.id}}">
                            {{option.text}}
                        </label>
                        {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <form action="" method="post" id="quiz-form">
            {% csrf_token %}
            <!-- hidden input field for score -->
            <input type="hidden" name="score" value="0" id="user-score">

            <!-- submit button -->
            <button type="submit" class="btn btn-primary" id="submit-button">Submit the quiz</button>
        </form>

    </div>

<script>
    // Elements
    var submitButton = document.getElementById("submit-button");
    var timerSpan = document.getElementById("timer");
    var quizForm = document.getElementById("quiz-form");
    var questions = document.querySelectorAll(".question");
    var userScoreInput = document.getElementById("user-score");

    quizDuration = (questions.length) * 60; // convert in seconds
    
    // Update Timer
    function updateTimer() {
        var minutes = Math.floor(quizDuration / 60);
        var seconds = quizDuration % 60;

        timerSpan.innerText = minutes + "m" + seconds + 's';

        // Check if the time ended
        if (quizDuration <= 0) {
            // Automatically Submit the quiz
            clearTimeout(quizTimerId);
            submitQuiz();
        } else if (document.getElementById("message-div")) {
            clearTimeout(quizTimerId);
            highlightCorrectAnswers();
        } else {
            // decrement the timer value by 1s
            quizDuration--;
        }
    }

    // Function to submit the quiz
    function submitQuiz() {
        // Calculate the score
        calculateScore();

        // Submit the quiz
        quizForm.submit();
    }

    // Check right answer and then calculate the score
    function calculateScore() {
        var score = 0;

        // Loop through each question
        questions.forEach(question => {
            var selectedInput = question.querySelector('input:checked');
            var correctAnswer = question.querySelector(".correct-answer").innerText;

            // Check if the answer is correct or not
            if (selectedInput && selectedInput.value === correctAnswer) {
                score += 1;
            }
        });

        // Update the hidden input field with score in form
        userScoreInput.value = score;
    }

    // highlight correct answer while showing result
    function highlightCorrectAnswers() {
        questions.forEach(question => {
            var correctAnswer = question.querySelector(".correct-answer");
            correctAnswer.previousElementSibling.querySelector("input").classList.add("bg-success");
            correctAnswer.previousElementSibling.classList.add("fw-bold");
        });

        // disable submit button
        submitButton.disabled = true;

        // disabel all options
        var options = document.querySelectorAll(".form-check-input");
        options.forEach(option => {
            option.disabled = true;
        });
    }

    // Attach Event Listener to Submit button
    submitButton.addEventListener("click", submitQuiz);

    // Timer Interval
    quizTimerId = setInterval(updateTimer, 1000);
</script>


{% endblock content %}